source "https://rubygems.org"

# Declare your gem's dependencies in curate=deposit.gemspec.
# Bundler will treat runtime dependencies like base dependencies, and
# development dependencies will be added by default to the :development group.
gemspec

# Declare any dependencies that are still in development here instead of in
# your gemspec. These might include edge Rails or gems from your path or
# Git. Remember to move these dependencies to your gemspec before releasing
# your gem to rubygems.org.

# To use debugger
# gem 'debugger'

gem 'debugger', group: [:development, :test]
gem 'rspec', group: [:development, :test]
gem 'rspec-rails', group: [:development, :test]
gem 'guard-bundler', group: [:development, :test]
gem 'guard-rails', group: [:development, :test]
gem 'guard-rspec', group: [:development, :test]
gem 'ruby_gntp', group: [:development, :test]
