development: &DEFAULT
  admin_usernames:
  - <%= ENV['USER'] %>
  - jeremy.n.friesen@gmail.com
test: &TEST
  <<: *DEFAULT
  admin_usernames:
  - <%= ENV['USER'] %>
  - an_admin_username
ci:
  <<: *TEST
